### ISSUE TITLE
avoid app-id clash

### ISSUE THREAD

**Issue by hboutemy** [sonatype-nexus-community/nexus-ci-examples#1]
current Nexus Example Builds app-ids clash with my existing ids

adding a prefix to the app-ids, like `NEB-` (for Nexus Example Builds), would ensure no clash happens

**Comment by hboutemy** [comment]
instead Updated IQ App ID to Jenkins Job Name "${env.JOB_BASE_NAME}", which is the Git branch name given the multi-branch job used

**Comment by mitunzavery** [comment]
IQ App IDs are now Jenkins Job Names
